### ISSUE TITLE
npm ERR! code ENOENT

### ISSUE THREAD

**Issue by Viren2809** [digital-asset/wallet-sample-app#12]
**ENOENT**: no such file or directory, open '/wallet-sample-app/ui/node_modules/@daml.js/40f452260bef3f29dede136108fc08a88d5a5250310281067087da6f0baddff7/package.json'

please provide a solution.

**Comment by alexputkov-da** [comment]
@Viren2809 
I think this error likely indicates that you either skipped step 2 (running "make codegen") under Build Required Files section in the local deployment instructions in the Readme, or this step didn't succeed for some reason, or perhaps the steps in the deployment instructions weren't followed in order (step 2 must be executed after step 1, and step 3 after step 2).
I suggest you run "make clean" and try following the deployment instructions again.
If you still encounter the same error, could you please provide more details? List the steps you were able to execute successfully all the way up to the point when you encountered the error.

**Comment by Viren2809** [comment]
@alexputkov-da 
Hi , Thanks for the solution, I cleaned everything & rerun the codegen after build. its working now.
