### ISSUE TITLE
Coin Asset Created in DA Wallet Further Inquiry

### ISSUE THREAD

**Issue by jsim77** [digital-asset/wallet-sample-app#21]
Dear Support,

My apology as I can't seem to find ways to ask around. Would like to ask since Coins were created as an Asset in DA Wallet, they don't represent or they are not a cryptocurrency too, do you think is there possible for this app to connect with a Fiat Wallet? 

Like for example Coins Asset in DA Wallet to send to other Fiat Wallet? Or exchange the Coins Asset for a Fiat Currency?

Should you think that the above question is not suitable here, can you direct or provide me the right source of community for me to ask?

Looking forward to your response.

Thank you.

**Comment by alexputkov-da** [comment]
@jsim77, this application is a reference app for Daml programming language. It is intended to be a learning tool for new Daml developers. It is not intended for use in production or to facilitate any real world use cases. As you observed, any user of this application can define a new asset type and issue any amount of this asset at any time. This alone makes this application not suitable for working with fiat currency or any other real world asset. You can utilize the programming techniques exhibited in this app to create another Daml app, where you may have a representation of a fiat currency or another financial asset, and you can integrate that app with a fiat wallet. If this is what you're looking to do, I would suggest you take a look at the [Daml Finance library](https://github.com/digital-asset/daml-finance), which is an accelerator for such projects and which provides ready available building blocks for such applications.

**Comment by jsim77** [comment]
@alexputkov-da 

Thanks.
